export const users = [
  {
    id: "user-1",
    username: "testuser",
    fullName: "김예준",
    avatar: "https://picsum.photos/seed/avatar-testuser/150/150",
    bio: "일상과 작업 기록을 모아두는 공간\nNext.js로 다듬는 인스타그램 클론",
    website: "https://github.com/hebi10",
    postsCount: 12,
    followersCount: 3280,
    followingCount: 214,
    isFollowing: false,
    isOwnProfile: true,
    isVerified: false,
  },
  {
    id: "user-2",
    username: "film_archive",
    fullName: "Film Archive",
    avatar: "https://picsum.photos/seed/avatar-film/150/150",
    bio: "필름 사진과 조용한 오후의 색감",
    website: "https://example.com/film",
    postsCount: 48,
    followersCount: 12400,
    followingCount: 188,
    isFollowing: true,
    isOwnProfile: false,
    isVerified: true,
  },
  {
    id: "user-3",
    username: "daily_table",
    fullName: "Daily Table",
    avatar: "https://picsum.photos/seed/avatar-table/150/150",
    bio: "집밥, 카페, 주말 브런치 기록",
    website: "https://example.com/table",
    postsCount: 87,
    followersCount: 8920,
    followingCount: 310,
    isFollowing: false,
    isOwnProfile: false,
    isVerified: false,
  },
  {
    id: "user-4",
    username: "seoul_walks",
    fullName: "Seoul Walks",
    avatar: "https://picsum.photos/seed/avatar-seoul/150/150",
    bio: "서울 골목과 비 온 뒤의 거리",
    website: "https://example.com/seoul",
    postsCount: 65,
    followersCount: 15600,
    followingCount: 122,
    isFollowing: true,
    isOwnProfile: false,
    isVerified: false,
  },
  {
    id: "user-5",
    username: "ui_collective",
    fullName: "UI Collective",
    avatar: "https://picsum.photos/seed/avatar-ui/150/150",
    bio: "제품 화면, 작은 인터랙션, 좋은 레퍼런스",
    website: "https://example.com/ui",
    postsCount: 132,
    followersCount: 24100,
    followingCount: 94,
    isFollowing: false,
    isOwnProfile: false,
    isVerified: true,
  },
  {
    id: "user-6",
    username: "cafe_weekend",
    fullName: "Cafe Weekend",
    avatar: "https://picsum.photos/seed/avatar-cafe/150/150",
    bio: "주말마다 찾는 조용한 카페",
    website: "https://example.com/cafe",
    postsCount: 39,
    followersCount: 4210,
    followingCount: 166,
    isFollowing: false,
    isOwnProfile: false,
    isVerified: false,
  },
  {
    id: "user-7",
    username: "workspace_note",
    fullName: "Workspace Note",
    avatar: "https://picsum.photos/seed/avatar-workspace/150/150",
    bio: "책상 위 도구와 작업 루틴",
    website: "https://example.com/workspace",
    postsCount: 54,
    followersCount: 7380,
    followingCount: 201,
    isFollowing: true,
    isOwnProfile: false,
    isVerified: false,
  },
  {
    id: "user-8",
    username: "night_frames",
    fullName: "Night Frames",
    avatar: "https://picsum.photos/seed/avatar-night/150/150",
    bio: "밤 산책, 네온, 흐린 창문",
    website: "https://example.com/night",
    postsCount: 72,
    followersCount: 11900,
    followingCount: 145,
    isFollowing: false,
    isOwnProfile: false,
    isVerified: false,
  },
];

export const posts = [
  {
    id: "post-1",
    username: "film_archive",
    avatarUrl: users[1].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-1/1080/1080",
    description: "늦은 오후 빛이 좋아서 한 장 남겼어요.",
    likeCount: 1284,
    commentCount: 32,
    createdAt: "2026-07-03T04:10:00.000Z",
  },
  {
    id: "post-2",
    username: "daily_table",
    avatarUrl: users[2].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-2/1080/1080",
    description: "주말 브런치. 오늘은 천천히 먹기.",
    likeCount: 842,
    commentCount: 18,
    createdAt: "2026-07-03T02:40:00.000Z",
  },
  {
    id: "post-3",
    username: "seoul_walks",
    avatarUrl: users[3].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-3/1080/1080",
    description: "비 온 뒤 선명해진 거리.",
    likeCount: 2310,
    commentCount: 54,
    createdAt: "2026-07-02T15:35:00.000Z",
  },
  {
    id: "post-4",
    username: "testuser",
    avatarUrl: users[0].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-4/1080/1080",
    description: "포트폴리오용 인스타 클론 화면 다듬는 중.",
    likeCount: 512,
    commentCount: 11,
    createdAt: "2026-07-02T12:05:00.000Z",
  },
  {
    id: "post-5",
    username: "ui_collective",
    avatarUrl: users[4].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-5/1080/1080",
    description: "버튼 하나에도 상태가 필요하다는 걸 다시 확인한 날.",
    likeCount: 1940,
    commentCount: 46,
    createdAt: "2026-07-01T23:20:00.000Z",
  },
  {
    id: "post-6",
    username: "cafe_weekend",
    avatarUrl: users[5].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-6/1080/1080",
    description: "창가 자리에서 마신 첫 잔.",
    likeCount: 936,
    commentCount: 23,
    createdAt: "2026-07-01T08:15:00.000Z",
  },
  {
    id: "post-7",
    username: "workspace_note",
    avatarUrl: users[6].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-7/1080/1080",
    description: "오늘 작업 세팅. 필요한 것만 책상 위에.",
    likeCount: 721,
    commentCount: 14,
    createdAt: "2026-06-30T22:00:00.000Z",
  },
  {
    id: "post-8",
    username: "night_frames",
    avatarUrl: users[7].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-8/1080/1080",
    description: "밤에는 빛이 더 솔직하게 보여요.",
    likeCount: 1588,
    commentCount: 37,
    createdAt: "2026-06-30T13:20:00.000Z",
  },
  {
    id: "post-9",
    username: "film_archive",
    avatarUrl: users[1].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-9/1080/1080",
    description: "기록해두면 다시 보고 싶은 장면.",
    likeCount: 1740,
    commentCount: 27,
    createdAt: "2026-06-29T08:45:00.000Z",
  },
  {
    id: "post-10",
    username: "daily_table",
    avatarUrl: users[2].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-10/1080/1080",
    description: "작은 접시들로 채운 저녁.",
    likeCount: 1126,
    commentCount: 29,
    createdAt: "2026-06-28T10:15:00.000Z",
  },
  {
    id: "post-11",
    username: "seoul_walks",
    avatarUrl: users[3].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-11/1080/1080",
    description: "낡은 간판과 새로 난 길.",
    likeCount: 2014,
    commentCount: 42,
    createdAt: "2026-06-27T16:50:00.000Z",
  },
  {
    id: "post-12",
    username: "testuser",
    avatarUrl: users[0].avatar,
    imageUrl: "https://picsum.photos/seed/insta-post-12/1080/1080",
    description: "피드 간격을 조금 줄이니 더 실제 앱 같아졌다.",
    likeCount: 689,
    commentCount: 16,
    createdAt: "2026-06-26T19:30:00.000Z",
  },
];

export const exploreContent = Array.from({ length: 30 }, (_, index) => ({
  id: `explore-${index + 1}`,
  username: users[(index + 1) % users.length].username,
  imageUrl: `https://picsum.photos/seed/explore-${index + 1}/600/600`,
  likeCount: 420 + index * 91,
  commentCount: 9 + index * 4,
  type: index % 6 === 0 ? "video" : "photo",
  createdAt: "2026-07-03T00:00:00.000Z",
}));

export const reels = [
  {
    id: "reel-1",
    username: "seoul_walks",
    avatar: users[3].avatar,
    description: "퇴근길 하늘 #서울 #산책",
    likeCount: 12400,
    commentCount: 182,
    isLiked: false,
    isFollowing: true,
  },
  {
    id: "reel-2",
    username: "daily_table",
    avatar: users[2].avatar,
    description: "아침 커피 루틴 #홈카페",
    likeCount: 7800,
    commentCount: 96,
    isLiked: true,
    isFollowing: false,
  },
  {
    id: "reel-3",
    username: "film_archive",
    avatar: users[1].avatar,
    description: "필름 색감 보정 전후 #photo",
    likeCount: 15100,
    commentCount: 241,
    isLiked: false,
    isFollowing: false,
  },
  {
    id: "reel-4",
    username: "ui_collective",
    avatar: users[4].avatar,
    description: "검색 패널 인터랙션 기록 #ui #prototype",
    likeCount: 9300,
    commentCount: 117,
    isLiked: false,
    isFollowing: false,
  },
  {
    id: "reel-5",
    username: "cafe_weekend",
    avatar: users[5].avatar,
    description: "비 오는 날 창가 자리 #cafe",
    likeCount: 6400,
    commentCount: 72,
    isLiked: false,
    isFollowing: false,
  },
  {
    id: "reel-6",
    username: "night_frames",
    avatar: users[7].avatar,
    description: "늦은 밤 횡단보도 #nightwalk",
    likeCount: 11800,
    commentCount: 153,
    isLiked: true,
    isFollowing: false,
  },
];

export const notifications = [
  {
    id: "noti-1",
    type: "like",
    username: "film_archive",
    avatarUrl: users[1].avatar,
    message: "님이 회원님의 게시물을 좋아합니다.",
    timestamp: "2026-07-03T05:20:00.000Z",
    isRead: false,
    postImageUrl: posts[3].imageUrl,
  },
  {
    id: "noti-2",
    type: "comment",
    username: "ui_collective",
    avatarUrl: users[4].avatar,
    message: "님이 댓글을 남겼습니다: 화면 간격 지금이 훨씬 자연스러워요.",
    timestamp: "2026-07-03T04:10:00.000Z",
    isRead: false,
    postImageUrl: posts[11].imageUrl,
  },
  {
    id: "noti-3",
    type: "follow",
    username: "daily_table",
    avatarUrl: users[2].avatar,
    message: "님이 회원님을 팔로우하기 시작했습니다.",
    timestamp: "2026-07-02T14:20:00.000Z",
    isRead: false,
    isFollowing: false,
  },
  {
    id: "noti-4",
    type: "comment",
    username: "seoul_walks",
    avatarUrl: users[3].avatar,
    message: "님이 댓글을 남겼습니다: 화면 진짜 인스타 같아요.",
    timestamp: "2026-07-02T09:00:00.000Z",
    isRead: true,
    postImageUrl: posts[3].imageUrl,
  },
  {
    id: "noti-5",
    type: "like",
    username: "cafe_weekend",
    avatarUrl: users[5].avatar,
    message: "님이 회원님의 게시물을 좋아합니다.",
    timestamp: "2026-07-01T20:45:00.000Z",
    isRead: true,
    postImageUrl: posts[0].imageUrl,
  },
  {
    id: "noti-6",
    type: "mention",
    username: "workspace_note",
    avatarUrl: users[6].avatar,
    message: "님이 댓글에서 회원님을 언급했습니다: @testuser 이 레이아웃 참고하기 좋아요.",
    timestamp: "2026-07-01T11:15:00.000Z",
    isRead: true,
    postImageUrl: posts[6].imageUrl,
  },
  {
    id: "noti-7",
    type: "follow",
    username: "night_frames",
    avatarUrl: users[7].avatar,
    message: "님이 회원님을 팔로우하기 시작했습니다.",
    timestamp: "2026-06-30T18:10:00.000Z",
    isRead: true,
    isFollowing: false,
  },
  {
    id: "noti-8",
    type: "like",
    username: "daily_table",
    avatarUrl: users[2].avatar,
    message: "님이 회원님의 게시물을 좋아합니다.",
    timestamp: "2026-06-30T07:35:00.000Z",
    isRead: true,
    postImageUrl: posts[11].imageUrl,
  },
  {
    id: "noti-9",
    type: "comment",
    username: "film_archive",
    avatarUrl: users[1].avatar,
    message: "님이 댓글을 남겼습니다: 피드 사진 톤이 좋아요.",
    timestamp: "2026-06-29T13:20:00.000Z",
    isRead: true,
    postImageUrl: posts[7].imageUrl,
  },
  {
    id: "noti-10",
    type: "like",
    username: "seoul_walks",
    avatarUrl: users[3].avatar,
    message: "님이 회원님의 게시물을 좋아합니다.",
    timestamp: "2026-06-28T23:40:00.000Z",
    isRead: true,
    postImageUrl: posts[3].imageUrl,
  },
];

export const chats = [
  {
    id: "chat-1",
    username: "film_archive",
    name: "Film Archive",
    avatar: users[1].avatar,
    lastMessage: "사진 그리드 간격 지금이 더 자연스러워요.",
    timestamp: "2026-07-03T03:40:00.000Z",
    unreadCount: 2,
    isOnline: true,
  },
  {
    id: "chat-2",
    username: "daily_table",
    name: "Daily Table",
    avatar: users[2].avatar,
    lastMessage: "피드 문구도 너무 길지 않게 가면 좋겠어요.",
    timestamp: "2026-07-02T22:20:00.000Z",
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: "chat-3",
    username: "seoul_walks",
    name: "Seoul Walks",
    avatar: users[3].avatar,
    lastMessage: "모바일 사이드바 확인해볼게요.",
    timestamp: "2026-07-01T19:10:00.000Z",
    unreadCount: 1,
    isOnline: true,
  },
  {
    id: "chat-4",
    username: "ui_collective",
    name: "UI Collective",
    avatar: users[4].avatar,
    lastMessage: "검색 패널 닫힘 동작만 있으면 더 좋아요.",
    timestamp: "2026-07-01T10:05:00.000Z",
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: "chat-5",
    username: "cafe_weekend",
    name: "Cafe Weekend",
    avatar: users[5].avatar,
    lastMessage: "알림 페이지는 배경을 더 덜어내도 괜찮을 듯해요.",
    timestamp: "2026-06-30T21:12:00.000Z",
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: "chat-6",
    username: "night_frames",
    name: "Night Frames",
    avatar: users[7].avatar,
    lastMessage: "릴스 더미도 몇 개 더 있으면 화면이 살아 보여요.",
    timestamp: "2026-06-29T18:32:00.000Z",
    unreadCount: 0,
    isOnline: false,
  },
];

const chatMessages = {
  "chat-1": [
    {
      id: "msg-1",
      senderId: "user2",
      senderName: "Film Archive",
      message: "사진 그리드 간격 지금이 더 자연스러워요.",
      timestamp: "2026-07-03T03:32:00.000Z",
      type: "text",
    },
    {
      id: "msg-2",
      senderId: "user1",
      senderName: "김예준",
      message: "피드 폭도 470px 기준으로 맞춰볼게요.",
      timestamp: "2026-07-03T03:35:00.000Z",
      type: "text",
    },
    {
      id: "msg-3",
      senderId: "user2",
      senderName: "Film Archive",
      message: "좋아요. 더미 데이터도 고정되어 있으니 포트폴리오에서 안정적으로 보이겠어요.",
      timestamp: "2026-07-03T03:40:00.000Z",
      type: "text",
    },
  ],
  "chat-2": [
    {
      id: "msg-4",
      senderId: "user3",
      senderName: "Daily Table",
      message: "피드 문구도 너무 길지 않게 가면 좋겠어요.",
      timestamp: "2026-07-02T22:20:00.000Z",
      type: "text",
    },
  ],
  "chat-3": [
    {
      id: "msg-5",
      senderId: "user4",
      senderName: "Seoul Walks",
      message: "모바일 사이드바 확인해볼게요.",
      timestamp: "2026-07-01T19:10:00.000Z",
      type: "text",
    },
  ],
  "chat-4": [
    {
      id: "msg-6",
      senderId: "user5",
      senderName: "UI Collective",
      message: "검색 패널 닫힘 동작만 있으면 더 좋아요.",
      timestamp: "2026-07-01T10:05:00.000Z",
      type: "text",
    },
  ],
  "chat-5": [
    {
      id: "msg-7",
      senderId: "user6",
      senderName: "Cafe Weekend",
      message: "알림 페이지는 배경을 더 덜어내도 괜찮을 듯해요.",
      timestamp: "2026-06-30T21:12:00.000Z",
      type: "text",
    },
  ],
  "chat-6": [
    {
      id: "msg-8",
      senderId: "user8",
      senderName: "Night Frames",
      message: "릴스 더미도 몇 개 더 있으면 화면이 살아 보여요.",
      timestamp: "2026-06-29T18:32:00.000Z",
      type: "text",
    },
  ],
};

export function findUser(username: string) {
  return users.find((user) => user.username === username) ?? users[0];
}

export function getUserPosts(username: string) {
  const selected = posts.filter((post) => post.username === username);
  return selected.length > 0 ? selected : posts.slice(0, 6);
}

export function getChat(chatId: string) {
  const chat = chats.find((item) => item.id === chatId) ?? chats[0];
  const user = users.find((item) => item.username === chat.username) ?? users[1];

  return {
    id: chat.id,
    username: chat.username,
    fullName: chat.name,
    avatarUrl: chat.avatar,
    isOnline: chat.isOnline,
    lastSeen: chat.timestamp,
    messages: chatMessages[chat.id as keyof typeof chatMessages] ?? [],
    user,
  };
}

export function searchMockData(query: string) {
  const normalized = query.trim().toLowerCase();
  const matchedUsers = normalized
    ? users.filter((user) =>
        [user.username, user.fullName, user.bio].some((value) =>
          value.toLowerCase().includes(normalized)
        )
      )
    : users;

  return {
    users: matchedUsers.map((user) => ({
      id: user.id,
      username: user.username,
      fullName: user.fullName,
      avatar: user.avatar,
      isVerified: user.isVerified,
      followersCount: user.followersCount,
      bio: user.bio,
    })),
    hashtags: ["instagram", "daily", "photo", "seoul", "portfolio", "ui", "cafe", "night"]
      .filter((tag) => !normalized || tag.includes(normalized))
      .map((tag, index) => ({
        id: `tag-${tag}`,
        tag,
        postCount: 1200 + index * 430,
      })),
    places: [
      { id: "place-1", name: "Seoul", category: "City", postCount: 9800 },
      { id: "place-2", name: "Hapjeong", category: "Neighborhood", postCount: 2100 },
      { id: "place-3", name: "Seongsu", category: "Neighborhood", postCount: 3400 },
      { id: "place-4", name: "Mangwon", category: "Neighborhood", postCount: 1800 },
    ],
  };
}
